import{i as a,a as y,S as L}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&u(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const f="48552658-8d0576f2bce30f826d9dd5e42",g=document.querySelector(".search-input"),w=document.querySelector(".search-button"),m=document.querySelector(".gallery"),i=document.querySelector(".loader"),l=document.querySelector(".load-more");let n=1,d=0,p;w.addEventListener("click",()=>{const r=g.value.trim();r?(n=1,q(r)):a.warning({title:"Warning",message:"Please enter a valid search term!",position:"topRight"})});l.addEventListener("click",function(){const r=g.value.trim();r&&(n++,v(r))});async function q(r){i.style.display="block",m.innerHTML="",l.style.display="none";try{const e=(await y.get("https://pixabay.com/api/",{params:{key:f,q:r,image_type:"photo",per_page:40,page:n}})).data;if(d=e.totalHits,e.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),i.style.display="none";return}h(e.hits),i.style.display="none",n*40<d&&(l.style.display="block"),b()}catch(o){a.error({title:"Error",message:"An error occurred while loading images!",position:"topRight"}),console.error("Error:",o),i.style.display="none"}}async function v(r){i.style.display="block";try{const e=(await y.get("https://pixabay.com/api/",{params:{key:f,q:r,image_type:"photo",per_page:40,page:n}})).data;h(e.hits),i.style.display="none",n*40>=d&&(l.style.display="none",a.info({title:"Info",message:"You have reached the end of the results.",position:"topRight"})),b()}catch(o){a.error({title:"Error",message:"An error occurred while loading more images!",position:"topRight"}),console.error("Error:",o),i.style.display="none"}}function h(r){let o="";r.forEach(e=>{o+=`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" />
        <div class="image-info">
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      </a>
    `}),m.innerHTML+=o}function b(){p?p.refresh():p=new L(".gallery a")}
//# sourceMappingURL=index.js.map
