import{i as n,a as u,S as h}from"./assets/vendor-tnUJPedx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const y="48552658-8d0576f2bce30f826d9dd5e42",f=document.querySelector(".search-input"),b=document.querySelector(".search-button"),g=document.querySelector(".gallery"),i=document.querySelector(".loader"),l=document.querySelector(".load-more");let a=1,p=0;b.addEventListener("click",()=>{const r=f.value.trim();r?(a=1,L(r)):n.warning({title:"Warning",message:"Please enter a valid search term!",position:"topRight"})});l.addEventListener("click",function(){const r=f.value.trim();r&&(a++,w(r))});async function L(r){i.style.display="block",g.innerHTML="",l.style.display="none";try{const e=(await u.get("https://pixabay.com/api/",{params:{key:y,q:r,image_type:"photo",per_page:40,page:a}})).data;if(p=e.totalHits,e.hits.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(e.hits),i.style.display="none",a*40<p&&(l.style.display="block")}catch(o){n.error({title:"Error",message:"An error occurred while loading images!",position:"topRight"}),console.error("Error:",o),i.style.display="none"}}async function w(r){i.style.display="block";try{const e=(await u.get("https://pixabay.com/api/",{params:{key:y,q:r,image_type:"photo",per_page:40,page:a}})).data;m(e.hits),i.style.display="none",a*40>=p&&(l.style.display="none",n.info({title:"Info",message:"You have reached the end of the results.",position:"topRight"}))}catch(o){n.error({title:"Error",message:"An error occurred while loading more images!",position:"topRight"}),console.error("Error:",o),i.style.display="none"}}function m(r){let o="";r.forEach(e=>{o+=`
      <a href="${e.largeImageURL}" class="gallery-item">
        <img src="${e.webformatURL}" alt="${e.tags}" />
        <div class="image-info">
          <p>Likes: ${e.likes}</p>
          <p>Views: ${e.views}</p>
          <p>Comments: ${e.comments}</p>
          <p>Downloads: ${e.downloads}</p>
        </div>
      </a>
    `}),g.innerHTML+=o,v()}let q=new h(".gallery a");function v(){q.refresh()}
//# sourceMappingURL=index.js.map
